In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv('glassdoor_jobs.csv')

In [10]:
data.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\r\nLocation: Albuquerque, NM\r\...",3.8,Tecolote Research\r\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\r\n\r\nI. General Summary\r\...,3.4,University of Maryland Medical System\r\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\r\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\r\nJob ID: 310709\r...,3.8,PNNL\r\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\r\nAffinity Solutions / Marketi...,2.9,Affinity Solutions\r\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [11]:
data.isnull().sum()

Unnamed: 0           0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

#### Salary Pursing
#### Company Name text only
#### State Field
#### Age of Company
#### Job Description

In [12]:
data = data.drop(columns = ['Unnamed: 0'])
data = data[data['Salary Estimate'] != '-1']

In [15]:
data.shape

(742, 14)

In [17]:
data['Salary Estimate'] = data['Salary Estimate'].apply(lambda x: x.split("(")[0])

In [22]:
data['Salary Estimate'].unique()

array(['$53K-$91K ', '$63K-$112K ', '$80K-$90K ', '$56K-$97K ',
       '$86K-$143K ', '$71K-$119K ', '$54K-$93K ', '$86K-$142K ',
       '$38K-$84K ', '$120K-$160K ', '$126K-$201K ', '$64K-$106K ',
       '$106K-$172K ', '$46K-$85K ', '$83K-$144K ', '$102K-$190K ',
       '$67K-$137K ', '$118K-$189K ', '$110K-$175K ', '$64K-$111K ',
       '$81K-$130K ', '$73K-$119K ', '$86K-$139K ', '$63K-$105K ',
       '$109K-$177K ', '$63K-$110K ', '$75K-$124K ', '$34K-$61K ',
       '$72K-$120K ', '$93K-$149K ', '$85K-$140K ', '$77K-$135K ',
       '$82K-$132K ', '$83K-$137K ', '$115K-$180K ', '$74K-$138K ',
       '$64K-$112K ', '$68K-$129K ', '$52K-$113K ', '$110K-$150K',
       'Employer Provided Salary:$150K-$160K', '$158K-$211K ',
       '$20K-$39K ', '$56K-$117K ', '$63K-$99K ', '$68K-$114K ',
       '$41K-$95K ', '$86K-$144K ', '$80K-$139K ', '$56K-$95K ',
       '$120K-$189K ', '$111K-$176K ', '$84K-$146K ', '$107K-$172K ',
       '$49K-$85K ', '$61K-$109K ', '$88K-$148K ', '$60K-$99K ',
       '$41K-$72K ', '$96K-$161K ', '$65K-$130K ', '$52K-$81K ',
       '$139K-$220K ', '$50K-$102K ', '$85K-$139K ', '$74K-$122K ',
       '$99K-$157K ', '$79K-$222K ', '$57K-$118K ', '$86K-$141K ',
       '$94K-$154K ', '$37K-$76K ', '$100K-$160K ', '$55K-$100K ',
       '$60K-$114K ', '$39K-$68K ', '$64K-$107K ', '$31K-$65K ',
       '$34K-$62K ', '$117K-$231K ', '$79K-$134K ', '$52K-$93K ',
       '$55K-$116K ', '$72K-$123K ', '$74K-$124K ', '$40K-$73K ',
       '$102K-$164K ', '$89K-$153K ', '$61K-$110K ', '$65K-$110K ',
       '$200K-$275K', '$68K-$123K ', '$80K-$129K ', '$39K-$71K ',
       '$38K-$85K ', '$121K-$193K ', '$54K-$102K ', '$102K-$163K ',
       '$76K-$140K ', '$60K-$101K ', '$82K-$133K ', '$65K-$125K ',
       '$91K-$148K ', '$95K-$173K ', '$77K-$124K ', '$80K-$135K ',
       '$85K-$159K ', '$80K-$105K', '$43K-$81K ', '$29K-$50K ',
       '$26K-$55K ', '$61K-$118K ', '$60K-$102K ', '$112K-$182K ',
       '$51K-$112K ', '$113K-$223K ', '$72K-$129K ', '$71K-$123K ',
       'Employer Provided Salary:$120K-$145K', '$80K-$120K ',
       '$80K-$130K ', '$59K-$115K ', '$71K-$136K ', '$81K-$167K ',
       '$71K-$204K ', '$75K-$125K ', '$77K-$136K ', '$74K-$123K ',
       '$44K-$78K ', '$65K-$148K ', '$59K-$110K ', '$85K-$134K ',
       '$124K-$204K ', '$131K-$207K ', '$110K-$174K ', '$52K-$101K ',
       '$81K-$133K ', '$132K-$211K ', '$74K-$140K ', '$100K-$190K ',
       '$43K-$80K ', '$17-$24 Per Hour', '$91K-$149K ', '$42K-$82K ',
       '$116K-$185K ', '$59K-$116K ', '$48K-$95K ', '$31K-$72K ',
       '$105K-$198K ', '$98K-$182K ', '$73K-$124K ',
       'Employer Provided Salary:$200K-$250K', '$21-$34 Per Hour',
       '$117K-$206K ', '$111K-$183K ', '$81K-$159K ', '$83K-$166K ',
       '$114K-$182K ', '$42K-$76K ', '$114K-$179K ', '$60K-$123K ',
       '$100K-$166K ', '$108K-$173K ', '$48K-$93K ', '$54K-$115K ',
       '$60K-$127K ', '$90K-$179K ', '$138K-$224K ', '$190K-$220K',
       '$35K-$62K ', '$18-$25 Per Hour', '$39K-$66K ', '$42K-$86K ',
       '$69K-$127K ', '$40K-$68K ', '$49K-$113K ', '$75K-$140K ',
       '$66K-$112K ', '$76K-$125K ', '$44K-$86K ', '$15-$25 Per Hour',
       '$53K-$92K ', '$65K-$120K ', '$60K-$103K ', '$53K-$105K ',
       '$33K-$62K ', '$48K-$90K ', '$34K-$64K ', '$66K-$111K ',
       '$91K-$138K ', '$62K-$114K ', '$71K-$129K ', '$74K-$119K ',
       '$55K-$97K ', '$15K-$16K', '$61K-$106K ', '$127K-$199K ',
       '$74K-$126K ', '$33K-$72K ', '$37K-$63K ', '$67K-$119K ',
       '$72K-$117K ', '$78K-$126K ', '$116K-$194K ', '$83K-$133K ',
       '$45K-$82K ', '$83K-$135K ', '$70K-$122K ', '$70K-$132K ',
       '$54K-$101K ', '$68K-$112K ', '$42K-$74K ', '$95K-$161K ',
       '$76K-$126K ', '$108K-$176K ', '$130K-$208K ', '$37K-$68K ',
       '$52K-$99K ', '$105K-$173K ', '$71K-$134K ', '$39K-$82K ',
       '$88K-$162K ', '$55K-$99K ', '$67K-$117K ', '$92K-$150K ',
       '$116K-$209K ', '$38K-$82K ', 'Employer Provided Salary:$85K-$90K',
       '$62K-$119K ', '$84K-$136K ', '$52K-$89K ', '$65K-$119K ',
       '$63K-$101K ', '$127K-$202K ', '$31K-$57K ', '$75K-$143K ',
       '$105K-$194K ', '$45K-$86K ', '$95K-$154K ', '$80K-$148K ',
       '$36K-$62K ', '$50K-$92K ', '$67K-$135K ', '$42K-$80K ',
       '$68K-$139K ', '$34K-$92K ', '$54K-$71K ', '$65K-$124K ',
       '$109K-$200K ', '$61K-$113K ', '$43K-$86K ', '$74K-$149K ',
       '$113K-$196K ', '$97K-$160K ', '$24-$39 Per Hour', '$102K-$172K ',
       '$108K-$171K ', '$76K-$142K ', '$202K-$306K ', '$49K-$97K ',
       '$65K-$134K ', '$32K-$59K ', '$87K-$158K ', '$107K-$173K ',
       '$56K-$99K ', 'Employer Provided Salary:$25-$28 Per Hour',
       '$80K-$155K ', '$43K-$98K ', '$45K-$78K ', '$44K-$96K ',
       '$50K-$110K ', '$61K-$119K ',
       'Employer Provided Salary:$100K-$140K', '$56K-$91K ',
       '$101K-$158K ', '$125K-$210K ', '$43K-$77K ', '$139K-$221K ',
       '$78K-$147K ', '$37K-$66K ', '$38K-$64K ', '$43K-$82K ',
       '$90K-$110K', '$93K-$151K ', '$40K-$101K ', '$97K-$180K ',
       '$81K-$134K ', '$84K-$157K ', '$121K-$203K ', '$52K-$85K ',
       '$81K-$140K ', '$83K-$148K ', '$31K-$55K ', '$102K-$178K ',
       'Employer Provided Salary:$110K-$130K', '$48K-$85K ',
       '$66K-$123K ', '$92K-$146K ', '$21-$29 Per Hour',
       '$10-$17 Per Hour', '$150K-$239K ', '$52K-$91K ', '$82K-$129K',
       '$47K-$101K ', '$49K-$76K ', '$43K-$88K ', '$124K-$199K ',
       '$97K-$181K ', '$100K-$173K ', '$53K-$96K ', '$65K-$96K ',
       '$75K-$127K ', '$94K-$139K ', '$176K-$289K ', '$92K-$149K ',
       '$118K-$188K ', '$108K-$146K ', '$65K-$106K ', '$55K-$98K ',
       '$94K-$162K ', '$63K-$120K ', '$126K-$228K ', '$80K-$134K ',
       '$85K-$142K ', '$87K-$140K ', '$76K-$127K ', '$54K-$92K ',
       '$61K-$100K ', '$112K-$179K ', '$63K-$111K ', '$75K-$126K ',
       '$110K-$184K ', '$76K-$145K ', '$70K-$118K ', '$94K-$153K ',
       '$150K-$180K ', '$42K-$77K ', '$47K-$85K ', '$62K-$112K ',
       '$64K-$108K ', '$89K-$144K ', '$55K-$105K ', '$135K-$211K ',
       '$57K-$80K ', '$129K-$215K ', '$63K-$127K ', '$50K-$89K ',
       '$71K-$124K ', '$69K-$121K ', '$150K-$238K ', '$77K-$132K ',
       '$59K-$112K ', '$35K-$65K ', '$79K-$147K ', '$119K-$187K ',
       '$90K-$157K ', '$32K-$62K ', '$116K-$208K ', '$102K-$165K ',
       '$91K-$159K ', '$80K-$133K ', '$39K-$69K ', '$27K-$48K ',
       '$36K-$71K ', '$130K-$206K ', '$99K-$178K ', '$86K-$137K ',
       '$37K-$100K ', '$58K-$111K ', '$72K-$133K ', '$61K-$126K ',
       '$95K-$160K ', '$33K-$61K ', '$69K-$119K ', '$67K-$127K ',
       '$66K-$117K ', '$50K-$98K ', '$90K-$153K ',
       'Employer Provided Salary:$100K-$135K', '$42K-$79K ',
       '$84K-$153K ', '$44K-$73K ', '$40K-$87K ', '$72K-$142K ',
       '$74K-$137K ', '$57K-$109K ', '$136K-$208K ', '$171K-$272K ',
       '$65K-$126K ', '$118K-$228K ', '$113K-$182K ', '$58K-$104K ',
       '$58K-$108K ', '$81K-$161K ', '$115K-$220K ', '$71K-$144K ',
       '$32K-$57K ', '$79K-$136K ', '$48K-$113K ', '$27-$47 Per Hour',
       '$68K-$125K ', '$39K-$67K ', '$71K-$135K ', '$61K-$123K ',
       '$87K-$141K ', '$71K-$121K ', '$72K-$121K ', '$51K-$88K ',
       '$101K-$141K ', '$79K-$127K ', '$81K-$132K ',
       'Employer Provided Salary:$120K-$140K', '$65K-$113K ',
       '$59K-$125K ', '$80K-$142K ', '$62K-$113K '], dtype=object)